language: php

php:
 - 5.3
 - 5.4

branches:
  only:
    - master

before_script:
 - composer selfupdate
 - composer install

script: vendor/bin/phpunit -c phpunit.xml

notifications:
  email: szlagowskipatryk+travis+notification@gmail.com